kind: live
name: Run registry browser
author: Alexey Naiden
descr: runs Neu.ro registry browser and opens it in default web browser

inputs:
  job_name:
    descr: Predictible subdomain name, which replaces JobID in the full job URI
    default: ""
  image:
    descr: image name
  http_auth:
    descr: whether to use http auth for jupter
    default: "True"

job:
    image: ${{ inputs.image }}
    name: ${{ inputs.job_name }}
    preset: cpu-small
    http_port: 8080
    http_auth: ${{ inputs.http_auth }}
    browse: True
    detach: True