kind: live
name: Run registry browser
author: Alexey Naiden
descr: runs Neu.ro registry browser and opens it in default web browser

inputs:
  job_name:
    descr: Predictible subdomain name, which replaces JobID in the full job URI
    default: ""
  http_auth:
    descr: whether to use http auth for browser
    default: "True"

job:
    image: neuromation/docker-registry-frontend
    name: ${{ inputs.job_name }}
    preset: cpu-small
    http_port: 80
    http_auth: ${{ inputs.http_auth }}
    browse: True
    detach: True